use clap::{Args, Parser, Subcommand};
use console::style;
use std::fs;
use std::path::PathBuf;
use ym_core::{AudioPlayer, DeltaCompiler, HzOption, SfxSequence, SystemHz};

#[derive(Parser, Debug)]
#[command(
    name = "ym-sfx",
    version,
    about = "YM-2149 Sound Effect Toolchain",
    long_about = None
)]
struct SfxCli {
    #[command(subcommand)]
    command: SfxCommands,
}

/// Arguments shared by every SFX subcommand that loads a source file.
#[derive(Args, Debug)]
struct SfxCommonArgs {
    /// Input source file path (.json, .csv, .afx, .afb, .yfx) or compiled .yfx binary path
    #[arg(short, long)]
    input: PathBuf,

    /// Timing refresh rate override (50 or 60 Hz)
    #[arg(long, value_enum)]
    hz: Option<HzOption>,

    /// Source chip clock in Hz. Defaults to 1773400 (ZX Spectrum) for AYFX formats. Override if your source uses a different clock.
    #[arg(long)]
    clock: Option<u32>,

    /// Effect index within an .afb bank file (0-based, default 0)
    #[arg(long, default_value_t = 0)]
    index: usize,
}

#[derive(Subcommand, Debug)]
enum SfxCommands {
    /// Render a sound effect source file into compiled YM-2149 binary payload
    Render {
        #[command(flatten)]
        common: SfxCommonArgs,

        /// Output compiled binary file path (.yfx)
        #[arg(short, long)]
        output: Option<PathBuf>,
    },
    /// Audition and play a sound effect sequence
    Play {
        #[command(flatten)]
        common: SfxCommonArgs,
    },
}

fn load_sfx_sequence(
    input: &std::path::Path,
    bank_index: usize,
) -> Result<SfxSequence, Box<dyn std::error::Error>> {
    let extension = input.extension().and_then(|ext| ext.to_str()).unwrap_or("");
    let name = input.file_stem().and_then(|s| s.to_str()).unwrap_or("sfx");

    match extension {
        "csv" => {
            let content = fs::read_to_string(input)?;
            SfxSequence::from_ayfx_csv(name, &content)
        }
        "afb" => {
            let bytes = fs::read(input)?;
            let bank = SfxSequence::from_ayfx_bank(&bytes)?;
            if bank.is_empty() {
                return Err("AYFX bank contains no sound effects".into());
            }
            if bank.len() > 1 {
                println!(
                    "{} {} sound effects (use --index 0..{} to select, using {}).",
                    style("Loaded AYFX bank with").dim(),
                    style(bank.len()).bold(),
                    bank.len() - 1,
                    bank_index,
                );
            }
            let idx = bank_index.min(bank.len() - 1);
            Ok(bank[idx].clone())
        }
        "afx" => {
            let bytes = fs::read(input)?;
            SfxSequence::from_ayfx_effect(name, &bytes)
        }
        "yfx" => {
            let bytes = fs::read(input)?;
            SfxSequence::from_yfx(name, &bytes)
        }
        "json" => {
            let content = fs::read_to_string(input)?;
            Ok(serde_json::from_str(&content)?)
        }
        _ => Err(format!(
            "Unsupported file extension '.{}' for SFX source. Expected .csv, .afb, .afx, .yfx, or .json",
            extension
        )
            .into()),
    }
}

fn apply_clock(sequence: &mut SfxSequence, clock: Option<u32>) {
    if let Some(c) = clock {
        sequence.source_clock = c;
    }
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let cli = SfxCli::parse();

    match cli.command {
        SfxCommands::Render {
            common:
                SfxCommonArgs {
                    input,
                    hz,
                    clock,
                    index,
                },
            output,
        } => {
            let output_path = output.unwrap_or_else(|| {
                let mut path = input.clone();
                path.set_extension("yfx");
                path
            });

            println!(
                "{} {}...",
                style("LOADING:").bold().cyan(),
                style(input.display()).cyan()
            );

            let mut sequence = load_sfx_sequence(&input, index)?;
            apply_clock(&mut sequence, clock);

            if let Some(hz_override) = hz {
                sequence.source_hz = SystemHz::from(hz_override).hz_value();
            }

            let compiler = DeltaCompiler::new();
            let binary = compiler.compile_sfx(&sequence);

            fs::write(&output_path, &binary)?;

            let (delay_y, delay_x) = ym_core::calculate_delay(sequence.source_hz);
            let yfi_path = output_path.with_extension("yfi");
            let yfi_contents = format!(
                "; ca65 include generated by ym-sfx for {}\n\
                 MAX_FRAMES   = {}\n\
                 PLAYER_HZ    = {}\n\
                 MASTER_CLOCK = {}\n\
                 YM_DELAY     = {}\n\
                 YM_FINE      = {}\n",
                input.display(),
                sequence.frames.len(),
                sequence.source_hz,
                sequence.source_clock,
                delay_y,
                delay_x,
            );
            fs::write(&yfi_path, yfi_contents)?;

            println!(
                "{} {} frames -> {} ({} bytes, {} Hz)",
                style("RENDER SUCCESS:").bold().green(),
                style(sequence.frames.len()).cyan(),
                style(output_path.display()).cyan(),
                style(binary.len()).cyan(),
                style(sequence.source_hz).cyan()
            );
            println!(
                "{} {} (YM_DELAY={}, YM_FINE={})",
                style("CA65 INCLUDE:").bold().green(),
                style(yfi_path.display()).cyan(),
                style(delay_y).cyan(),
                style(delay_x).cyan()
            );
        }
        SfxCommands::Play {
            common:
                SfxCommonArgs {
                    input,
                    hz,
                    clock,
                    index,
                },
        } => {
            let mut sequence = load_sfx_sequence(&input, index)?;
            apply_clock(&mut sequence, clock);

            if let Some(hz_override) = hz {
                sequence.source_hz = SystemHz::from(hz_override).hz_value();
            }

            println!(
                "{} {} ({} Hz)...",
                style("LOADING:").bold().cyan(),
                style(input.display()).cyan(),
                sequence.source_hz
            );

            AudioPlayer::play_sfx(&sequence)?;
        }
    }

    Ok(())
}
