; ============================================================
; maria.inc -- Atari 7800 Hardware Defines
; ============================================================

TIA         = $00
PTCTRL      = $01

INPT0       = $08
INPT1       = $09
INPT2       = $0A
INPT3       = $0B
INPT4       = $0C
INPT5       = $0D

AUDC0       = $15
AUDC1       = $16
AUDF0       = $17
AUDF1       = $18
AUDV0       = $19
AUDV1       = $1A

MARIA       = $20
BKGRND      = $20
BACKGRND    = $20
WSYNC       = $24
MSTAT       = $28
CTRL        = $3C

SWCHA       = $0280
CTLSWA      = $0281
SWCHB       = $0282
CTLSWB      = $0283
INTIM       = $0284
