; =========================================================
; main.s -- Atari 7800 Dual-Chip Audio Demo (YM-2149 + TIA)
; 5 Audio Channels: 3-Voice YM Music + 2-Voice TIA SFX
; ca65 / cc65 toolchain
; =========================================================

.include "maria.inc"
.include "ym2149.inc"
.include "ysg.inc"
.include "tfx.inc"

; Include ca65 header constants generated by lym for each effect
.include "star_raiders_laser.tfi"
.include "tia_explosion.tfi"
.include "tia_jump.tfi"
.include "tia_coin.tfi"

.segment "CODE"

PLAYER_ZP_BASE  = $80
NTSC_HZ         = 60

.ifndef PLAYER_HZ
PLAYER_HZ       = 50
.endif

; Zero-page variable aliases for YM-2149 background music player
music_ptr       = PLAYER_ZP_BASE + TPlayerState::music_ptr
pat_frames      = PLAYER_ZP_BASE + TPlayerState::pat_frames
seq_idx         = PLAYER_ZP_BASE + TPlayerState::seq_idx
tmp_mask        = PLAYER_ZP_BASE + TPlayerState::tmp_mask
pat_table       = PLAYER_ZP_BASE + TPlayerState::pat_table
pat_base        = PLAYER_ZP_BASE + TPlayerState::pat_base
seq_base        = PLAYER_ZP_BASE + TPlayerState::seq_base
pat_size        = PLAYER_ZP_BASE + TPlayerState::pat_size
seq_len         = PLAYER_ZP_BASE + TPlayerState::seq_len
loop_pat        = PLAYER_ZP_BASE + TPlayerState::loop_pat
last_pat_frames = PLAYER_ZP_BASE + TPlayerState::last_pat_frames
features        = PLAYER_ZP_BASE + TPlayerState::features
music_acc       = PLAYER_ZP_BASE + TPlayerState::music_acc
music_delta     = PLAYER_ZP_BASE + TPlayerState::music_delta
v_frame         = PLAYER_ZP_BASE + TPlayerState::v_frame
rle_count       = PLAYER_ZP_BASE + TPlayerState::rle_count

; Zero-page state for Atari TIA Sound Effects (Channels 0 & 1)
SFX0_PTR_L      = $A0
SFX0_PTR_H      = $A1
SFX0_ACTIVE     = $A2
SFX0_FRAMES     = $A3

SFX1_PTR_L      = $A4
SFX1_PTR_H      = $A5
SFX1_ACTIVE     = $A6
SFX1_FRAMES     = $A7

; Edge-detection controller state
PREV_FIRE1      = $A8
PREV_FIRE2      = $A9
PREV_JOY_UP     = $AA
PREV_JOY_DOWN   = $AB

.import music_data
.import laser_data
.import explosion_data
.import jump_data
.import coin_data

reset:
        sei
        cld
        ldx #$FF
        txs

        ; Lock INPTCTRL to 7800 mode and clear TIA VBLANK dump bit
        lda #$07
        sta PTCTRL
        lda #$00
        sta PTCTRL

        ; Clear Zero-Page variables
        ldx #$3F
        lda #0
cl_zp:  sta $80,x
        dex
        bpl cl_zp

        ; Silence YM-2149 registers (R0..R13 -> 0)
        ldx #NUM_REGS-1
cl_ym:  stx AY_ADDR
        lda #0
        sta AY_DATA
        dex
        bpl cl_ym

        ; Silence TIA audio registers
        lda #0
        sta AUDV0
        sta AUDV1
        sta AUDC0
        sta AUDC1
        sta AUDF0
        sta AUDF1

        ; Initialize background music player
        jsr init_music

main_loop:
        jsr sync_vbi
        jsr check_inputs

        ; --------------------------------------------------
        ; 1. Stream YM-2149 Background Music (Channels A, B, C)
        ; --------------------------------------------------
        lda music_delta
        ora music_delta+1
        beq play_now

        clc
        lda music_acc
        adc music_delta
        sta music_acc
        lda music_acc+1
        adc music_delta+1
        sta music_acc+1
        bcc skip_play

play_now:
        jsr play_frame
skip_play:

        ; --------------------------------------------------
        ; 2. Stream TIA Sound Effects (Channels 0 & 1)
        ; --------------------------------------------------
        jsr update_tia_sfx

        ; --------------------------------------------------
        ; 3. Visual Color Feedback (MARIA BKGRND)
        ; --------------------------------------------------
        jsr update_visuals

        jmp main_loop

; ----------------------------------------------------------
; VBI Sync
; ----------------------------------------------------------
sync_vbi:
v1:     bit MSTAT
        bmi v1
v2:     bit MSTAT
        bpl v2
        rts

; ----------------------------------------------------------
; check_inputs -- controller edge detection for SFX triggers
; ----------------------------------------------------------
check_inputs:
        ; --- Button 1 / Fire 1 (INPT4): Star Raiders Laser on TIA Ch 0 ---
        bit INPT4               ; Bit 7 = 0 when pressed, 1 when released
        bmi @f1_not_pressed

        lda PREV_FIRE1
        bne @check_f2

        lda #1
        sta PREV_FIRE1

        ; Trigger Star Raiders Laser on TIA Channel 0
        lda #<laser_data
        sta SFX0_PTR_L
        lda #>laser_data
        sta SFX0_PTR_H
        lda #star_raiders_laser::NUM_FRAMES
        sta SFX0_FRAMES
        lda #1
        sta SFX0_ACTIVE
        jmp @check_f2

@f1_not_pressed:
        lda #0
        sta PREV_FIRE1

@check_f2:
        ; --- Button 2 / Fire 2 (INPT0): Explosion on TIA Ch 1 ---
        bit INPT0               ; Bit 7 = 0 when pressed in 7800 2-button mode
        bmi @f2_not_pressed

        lda PREV_FIRE2
        bne @check_joy

        lda #1
        sta PREV_FIRE2

        ; Trigger Explosion on TIA Channel 1
        lda #<explosion_data
        sta SFX1_PTR_L
        lda #>explosion_data
        sta SFX1_PTR_H
        lda #tia_explosion::NUM_FRAMES
        sta SFX1_FRAMES
        lda #1
        sta SFX1_ACTIVE
        jmp @check_joy

@f2_not_pressed:
        lda #0
        sta PREV_FIRE2

@check_joy:
        ; --- Joystick Up (SWCHA bit 4): Arcade Jump Boing on TIA Ch 0 ---
        lda SWCHA
        and #%00010000          ; 0 = active pressed
        bne @up_not_pressed

        lda PREV_JOY_UP
        bne @check_down

        lda #1
        sta PREV_JOY_UP

        ; Trigger Jump on TIA Channel 0
        lda #<jump_data
        sta SFX0_PTR_L
        lda #>jump_data
        sta SFX0_PTR_H
        lda #tia_jump::NUM_FRAMES
        sta SFX0_FRAMES
        lda #1
        sta SFX0_ACTIVE
        jmp @check_down

@up_not_pressed:
        lda #0
        sta PREV_JOY_UP

@check_down:
        ; --- Joystick Down (SWCHA bit 5): Coin Chime on TIA Ch 0 ---
        lda SWCHA
        and #%00100000          ; 0 = active pressed
        bne @down_not_pressed

        lda PREV_JOY_DOWN
        bne @inputs_done

        lda #1
        sta PREV_JOY_DOWN

        ; Trigger Coin on TIA Channel 0
        lda #<coin_data
        sta SFX0_PTR_L
        lda #>coin_data
        sta SFX0_PTR_H
        lda #tia_coin::NUM_FRAMES
        sta SFX0_FRAMES
        lda #1
        sta SFX0_ACTIVE
        rts

@down_not_pressed:
        lda #0
        sta PREV_JOY_DOWN
@inputs_done:
        rts

; ----------------------------------------------------------
; update_tia_sfx -- streams 3-byte frames [AUDF, AUDC, AUDV]
; ----------------------------------------------------------
update_tia_sfx:
        ; --- Process TIA Channel 0 ---
        lda SFX0_ACTIVE
        beq @check_ch1
        cmp #2
        beq @sfx0_finish

        ldy #0
        lda (SFX0_PTR_L),y      ; Byte 0: AUDF0 (Frequency)
        sta AUDF0
        iny
        lda (SFX0_PTR_L),y      ; Byte 1: AUDC0 (Waveform Control)
        sta AUDC0
        iny
        lda (SFX0_PTR_L),y      ; Byte 2: AUDV0 (Volume)
        sta AUDV0

        ; Advance pointer by 3 bytes
        clc
        lda SFX0_PTR_L
        adc #3
        sta SFX0_PTR_L
        bcc @sfx0_ptr_ok
        inc SFX0_PTR_H
@sfx0_ptr_ok:
        dec SFX0_FRAMES
        bne @check_ch1

        ; Last frame just played in full; silence on the next tick
        ; instead of clobbering the volume we just wrote.
        lda #2
        sta SFX0_ACTIVE
        jmp @check_ch1

@sfx0_finish:
        lda #0
        sta AUDV0
        sta SFX0_ACTIVE

@check_ch1:
        ; --- Process TIA Channel 1 ---
        lda SFX1_ACTIVE
        beq @tia_done
        cmp #2
        beq @sfx1_finish

        ldy #0
        lda (SFX1_PTR_L),y      ; Byte 0: AUDF1 (Frequency)
        sta AUDF1
        iny
        lda (SFX1_PTR_L),y      ; Byte 1: AUDC1 (Waveform Control)
        sta AUDC1
        iny
        lda (SFX1_PTR_L),y      ; Byte 2: AUDV1 (Volume)
        sta AUDV1

        ; Advance pointer by 3 bytes
        clc
        lda SFX1_PTR_L
        adc #3
        sta SFX1_PTR_L
        bcc @sfx1_ptr_ok
        inc SFX1_PTR_H
@sfx1_ptr_ok:
        dec SFX1_FRAMES
        bne @tia_done

        ; Last frame just played in full; silence on the next tick
        ; instead of clobbering the volume we just wrote.
        lda #2
        sta SFX1_ACTIVE
        jmp @tia_done

@sfx1_finish:
        lda #0
        sta AUDV1
        sta SFX1_ACTIVE

@tia_done:
        rts

; ----------------------------------------------------------
; update_visuals -- dynamic backdrop color based on audio state
; ----------------------------------------------------------
update_visuals:
        lda SFX0_ACTIVE
        beq @ch0_idle

        ; Channel 0 active: check if Channel 1 is also active
        lda SFX1_ACTIVE
        beq @only_ch0
        lda #$0F                ; Bright White flash (Both active!)
        sta BKGRND
        rts

@only_ch0:
        lda #$9A                ; Electric Cyan flash (Ch 0 Laser / Jump / Coin)
        sta BKGRND
        rts

@ch0_idle:
        lda SFX1_ACTIVE
        beq @idle_bg
        lda #$3A                ; Blazing Orange flash (Ch 1 Explosion)
        sta BKGRND
        rts

@idle_bg:
        lda #$06                ; Deep Midnight Blue (Idle BGM playing)
        sta BKGRND
        rts

; ==========================================================
; YM-2149 YSG Background Music Engine
; ==========================================================

init_music:
        lda #0
        sta seq_idx
        sta pat_frames
        sta rle_count
        sta music_acc
        sta music_acc+1
        sta v_frame
        sta v_frame+1

        lda #<((PLAYER_HZ * 65536) / NTSC_HZ)
        sta music_delta
        lda #>((PLAYER_HZ * 65536) / NTSC_HZ)
        sta music_delta+1

        lda music_data + TYsgHeader::pat_size
        sta pat_size
        lda music_data + TYsgHeader::seq_len
        sta seq_len
        lda music_data + TYsgHeader::loop_pat
        sta loop_pat
        lda music_data + TYsgHeader::last_pat_frames
        sta last_pat_frames
        lda music_data + TYsgHeader::features
        sta features

        lda #<(music_data + .sizeof(TYsgHeader))
        sta seq_base
        lda #>(music_data + .sizeof(TYsgHeader))
        sta seq_base+1

        clc
        lda seq_base
        adc seq_len
        sta pat_table
        lda seq_base+1
        adc #0
        sta pat_table+1

        lda music_data + TYsgHeader::num_unique
        sta tmp_mask
        lda #0
        sta tmp_mask+1
        asl tmp_mask
        rol tmp_mask+1
        asl tmp_mask
        rol tmp_mask+1          ; tmp_mask = num_unique * 4
        clc
        lda pat_table
        adc tmp_mask
        sta pat_base
        lda pat_table+1
        adc tmp_mask+1
        sta pat_base+1

        rts

play_frame:
        lda rle_count
        beq not_rle_idle
        dec rle_count
        dec pat_frames
        rts

not_rle_idle:
        lda pat_frames
        bne do_play

        lda seq_idx
        cmp seq_len
        bcc load_pattern

        ; Loop or restart song
        lda loop_pat
        cmp #$FF
        bne do_loop
        jsr init_music
        rts

do_loop:
        sta seq_idx

load_pattern:
        ldy seq_idx
        lda (seq_base),y
        inc seq_idx

        sta tmp_mask
        lda #0
        sta tmp_mask+1
        asl tmp_mask
        rol tmp_mask+1
        asl tmp_mask
        rol tmp_mask+1          ; tmp_mask = idx * 4
        clc
        lda tmp_mask
        adc pat_table
        sta tmp_mask
        lda tmp_mask+1
        adc pat_table+1
        sta tmp_mask+1

        ldy #0
        lda (tmp_mask),y
        sta music_ptr
        iny
        lda (tmp_mask),y
        sta music_ptr+1

        clc
        lda music_ptr
        adc pat_base
        sta music_ptr
        lda music_ptr+1
        adc pat_base+1
        sta music_ptr+1

        lda last_pat_frames
        beq use_pat_size
        lda seq_idx
        cmp seq_len
        bne use_pat_size
        lda last_pat_frames
        sta pat_frames
        jmp do_play
use_pat_size:
        lda pat_size
        sta pat_frames

do_play:
        dec pat_frames

        ldy #0
        lda (music_ptr),y
        sta tmp_mask
        iny
        lda (music_ptr),y
        sta tmp_mask+1
        clc
        lda music_ptr
        adc #2
        sta music_ptr
        lda music_ptr+1
        adc #0
        sta music_ptr+1

        lda features
        lsr
        bcc rle_done
        bit tmp_mask+1
        bpl rle_done
        ldy #0
        lda (music_ptr),y
        inc music_ptr
        bne rle_ptr_done
        inc music_ptr+1
rle_ptr_done:
        sta rle_count
        rts
rle_done:
        ldx #0
reg_low:
        lda bit_table,x
        and tmp_mask
        beq next_low
        stx AY_ADDR
        ldy #0
        lda (music_ptr),y
        sta AY_DATA
        inc music_ptr
        bne next_low
        inc music_ptr+1
next_low:
        inx
        cpx #8
        bne reg_low

reg_high:
        txa
        and #$07
        tay
        lda bit_table,y
        and tmp_mask+1
        beq next_high
        stx AY_ADDR
        ldy #0
        lda (music_ptr),y
        sta AY_DATA
        inc music_ptr
        bne next_high
        inc music_ptr+1
next_high:
        inx
        cpx #NUM_REGS
        bne reg_high

        rts

bit_table:
        .byte $01, $02, $04, $08, $10, $20, $40, $80

.segment "VECTORS"
        .byte $FF, $83          ; Atari 7800 Encryption Header Signature Flag
        .word reset             ; NMI vector
        .word reset             ; RESET vector
        .word reset             ; IRQ vector
